### ISSUE TITLE
It not suppport Spring boot 2?

### ISSUE THREAD

**Issue by liaotup** [markhobson/rest-template-logger#5]
I use in Spring boot 2 but can't interception the reqeust!

**Comment by markhobson** [comment]
Hi, I've released 1.0.0 that targets Spring Boot 1.x and upgraded master to Spring Boot 2. The IT passes - what problems are you experiencing? If you could supply a failing test case then that'd help.

**Comment by liaotup** [comment]
The Interceptor of Logger could not catch any request from controller!

**Comment by markhobson** [comment]
Can you provide some code to demonstrate the problem that you're encountering please?

**Comment by markhobson** [comment]
Closing this until a problem can be demonstrated.
