### ISSUE TITLE
publish new version to maven

### ISSUE THREAD

**Issue by Marek00Malik** [markhobson/rest-template-logger#8]
The version registered to Maven is 0.1.0, where the release version here is 2.0.0

**Comment by markhobson** [comment]
Hi, I think you may be using the old artifact id `rest-template-logger` rather than the newer one `spring-rest-template-logger`. The latter is available on Maven Central at 2.0.0:

https://search.maven.org/artifact/org.hobsoft.spring/spring-rest-template-logger/2.0.0/jar

**Comment by markhobson** [comment]
Closing due to no response.
